tasks:
  - init: yarn && yarn build:contract
    command: yarn dev
ports:
  - port: 1234
    onOpen: open-browser
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    addCheck: true
    addComment: true
